[package]
name = "image_style"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "image_style_lib"

[dependencies]
image = "*"
clap = { version = "*", features = ["derive"] }
rayon = "*"
indicatif = { version = "*", features = ["rayon"] }